### ISSUE TITLE
error after exports fortune to excel 

### ISSUE THREAD

**Issue by puviyan-jayaraman** [Corbe30/FortuneExcel#17]
after export fortune to excel all  empty cell agetting NAN 

I attach my result for your reference
![Screenshot 2024-12-20 151658](https://github.com/user-attachments/assets/34037576-348e-4500-9348-5d6f2fbde212)

below i mage is getting error in excel downloaded fortune
![Screenshot 2024-12-20 155635](https://github.com/user-attachments/assets/693e93b8-fd53-4f57-8c34-71928048f742)  

real excel sheet is 
![Uploading Screenshot 2024-12-20 155823.png…]()

**Comment by Corbe30** [comment]
@puviyan-jayaraman released v1.2.3, can you please check if the issue is resolved
