### ISSUE TITLE
Minor changes requested

### ISSUE THREAD

**Issue by sanchit3008** [Corbe30/FortuneExcel#8]
<img width="149" alt="image" src="https://github.com/user-attachments/assets/2fb96e20-9d11-4b02-9e0b-f7d423f2dce9">

1. `xlsx` instead of `xlsl`
2. `Import` instead of `import`
3. Is it possible to filter only xlsx files in the file explorer when uploading a file?
4. Have you tried this with xls/csv? If yes then we can simple call the tooltip text `Import`

**Comment by Corbe30** [comment]
`xls` and `csv` are not supported. xls is a binary file, although csv will be easy to implement in another plugin.
